<?php
session_start();
include('includes/studenthead.php');
require 'vendor/autoload.php';

$username = $_SESSION['student_user'];


$authenticator = new PHPGangsta_GoogleAuthenticator();
// check if secret exist in session
$secret = $_SESSION['secret'];
if (!$secret) {
    $secret = $authenticator->createSecret();
    $_SESSION['secret'] = $secret;
}

$website = 'http://yabatech.com'; 
$title= 'Voting';
$qrCodeUrl = $authenticator->getQRCodeGoogleUrl($title, $secret,$website);

// echo $secret;


$sql= "SELECT * FROM staffs WHERE staff_id='$username'";
$result=mysqli_query($db,$sql) or die("could not select database");
$row=mysqli_fetch_array($result,MYSQLI_ASSOC);
$count=mysqli_num_rows($result);
if ($count!=1) {
    session_destroy();
    header('location:index.php');
}

if ($_POST['otpvalue']) {
    // echo $secret;

    $otpvalue = $_POST['otpvalue'];
    
    $checkResult = $authenticator->verifyCode($secret, $otpvalue, 2);

    if ($checkResult) {
        $_SESSION['login_user'] = $username;

        // echo($_SESSION);

        header('location:vote.php');
    } else {
        session_destroy();
        echo 'Failed verification!'; 
        header('location:index.php');
    }
}

?>
<!DOCTYPE html>
<html>
<title>OTP Confirmation</title>
<body>

<h3>Scan code and Enter the verification code generated by Google Authenticator app on your phone </h3>
<img src="<?= $qrCodeUrl ?>" />
<!-- <form action="otpprocess.php" method="post"> -->
<form method="POST" id="my_form" style="margin-top:100px;">

<input type="text" name="otpvalue" placeholder="Enter OTP to continue"/>
<input type="submit" value="Verify OTP"  />
</form>
</body>
</html> 